### ISSUE TITLE
Duplicated information in externalRefs section

### ISSUE THREAD

**Issue by prog8** [anchore/syft#1804] opened 2023-05-09 16:40 UTC
**What happened**:
I generated SBOM for react and see a lot of duplicates

```  {
   "name": "@babel/code-frame",
   "SPDXID": "SPDXRef-Package-npm--babel-code-frame-c7d8ac965211588b",
   "versionInfo": "7.0.0-beta.44",
   "downloadLocation": "NOASSERTION",
   "sourceInfo": "acquired package info from installed node module manifest file: react-18.2.0/fixtures/flight/yarn.lock",
   "licenseConcluded": "NONE",
   "licenseDeclared": "NONE",
   "copyrightText": "NOASSERTION",
   "externalRefs": [
    {
     "referenceCategory": "SECURITY",
     "referenceType": "cpe23Type",
     "referenceLocator": "cpe:2.3:a:\\@babel\\/code-frame:\\@babel\\/code-frame:7.0.0-beta.44:*:*:*:*:*:*:*"
    },
    {
     "referenceCategory": "SECURITY",
     "referenceType": "cpe23Type",
     "referenceLocator": "cpe:2.3:a:\\@babel\\/code-frame:\\@babel\\/code_frame:7.0.0-beta.44:*:*:*:*:*:*:*"
    },
    {
     "referenceCategory": "SECURITY",
     "referenceType": "cpe23Type",
     "referenceLocator": "cpe:2.3:a:\\@babel\\/code_frame:\\@babel\\/code-frame:7.0.0-beta.44:*:*:*:*:*:*:*"
    },
    {
     "referenceCategory": "SECURITY",
     "referenceType": "cpe23Type",
     "referenceLocator": "cpe:2.3:a:\\@babel\\/code_frame:\\@babel\\/code_frame:7.0.0-beta.44:*:*:*:*:*:*:*"
    },
    {
     "referenceCategory": "SECURITY",
     "referenceType": "cpe23Type",
     "referenceLocator": "cpe:2.3:a:\\@babel\\/code:\\@babel\\/code-frame:7.0.0-beta.44:*:*:*:*:*:*:*"
    },
    {
     "referenceCategory": "SECURITY",
     "referenceType": "cpe23Type",
     "referenceLocator": "cpe:2.3:a:\\@babel\\/code:\\@babel\\/code_frame:7.0.0-beta.44:*:*:*:*:*:*:*"
    },
    {
     "referenceCategory": "PACKAGE-MANAGER",
     "referenceType": "purl",
     "referenceLocator": "pkg:npm/%40babel/code-frame@7.0.0-beta.44"
    }
   ]
  },

```

**What you expected to happen**:

No duplicates

**Steps to reproduce the issue**:

1. Download facebook/react https://github.com/facebook/react/archive/refs/heads/main.zip
2. UNzip
3. Run syft packages react -o spdx-json

**Anything else we need to know?**:

**Environment**:

Application:        syft
Version:            0.79.0
JsonSchemaVersion:  7.1.4
BuildDate:          2023-04-21T16:20:25Z
GitCommit:          b2b332e8b2b66af0905e98b54ebd713a922be1a8
GitDescription:     v0.79.0
Platform:           linux/amd64
GoVersion:          go1.19.8
Compiler:           gc

**Comment by kzantow** [comment] 2023-05-25 20:30
Hi, @prog8 thanks for the report, but none of these are actually duplicates. Syft generates CPEs with different permutations including dashes `-` and underscores `_`. If you look at the CPEs you will see that there are differences in each of them. I'm going to close this issue due to this, but please reopen if I've missed anything! Thanks!

**Closed by kzantow** 2023-05-25 20:30 UTC
Labels: bug

**Comment by prog8** [comment] 2023-05-26 12:32
Thank you, @kzantow. I haven't noticed these differences. Then I have another question. Why do we have to build all the permutations of @babel/code-frame. In fact @babel/code-frame is something else then @babel/code_frame. Is it something that https://nvlpubs.nist.gov/nistpubs/Legacy/IR/nistir7695.pdf forces?

**Comment by kzantow** [comment] 2023-05-26 14:10
@prog8 the problem isn't so much the CPE spec, it's the fact that the naming used by [NVD](https://nvd.nist.gov/vuln) is fairly arbitrary and we need to test a lot of different CPE permutations to find [CVEs](https://www.cve.org/). If we knew definitively that a particular package is a specific CPE, we could add some handling [here](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/common/cpe/candidate_by_package_type.go#L22), but we try to use this only when needed.

That said -- what is the _correct_ CPE for `@babel/code-frame`? A Google search doesn't result in anything. If there haven't been any CVEs reported, there will never be a CPE generated, so we wouldn't even know the right one to use.
