### ISSUE TITLE
Syft does not detect java dependencies

### ISSUE THREAD

**Issue by stefanm8** [anchore/syft#702] opened 2021-12-17 13:15 UTC
**What happened**:

Running:
```
syft dir:.
```

**What you expected to happen**:

See java projects dependencies

**How to reproduce it (as minimally and precisely as possible)**:

```
syft dir:.
```

**Anything else we need to know?**:

running mvn dependency:tree i can see log4j
```
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.11.0:compile
[INFO] \- org.apache.logging.log4j:log4j-core:jar:2.11.0:compile
```

running syft:
```
 ✔ Indexed .
 ✔ Cataloged packages              [1 packages]
NAME      VERSION       TYPE
java-app  1.0-SNAPSHOT  java-archive
```

**Environment**:
- Output of `syft version`:
```
$ syft version
Application:   syft
Version:       0.33.0
BuildDate:     2021-12-16T14:16:33Z
GitCommit:     a27907659d6c43f5bef2f76a9e381f2bf697a64f
GitTreeState:  clean
Platform:      darwin/arm64
GoVersion:     go1.16.12
Compiler:      gc
```

- OS (e.g: `cat /etc/os-release` or similar):
OSX

Am I missing something?

**Comment by luhring** [comment] 2021-12-17 13:42
Hi @stefanm8 👋 thanks for opening this. Do you have a project we can use to reproduce what you're seeing?

Also, not sure if this applies here, but have you installed the dependencies yet? Right now Syft finds installations of of Java dependencies. There's a recent issue that describes finding Java dependencies even before they're installed using `pom.xml`: https://github.com/anchore/syft/issues/676

**Comment by stefanm8** [comment] 2021-12-19 08:38
Hi, I do not have the repository, will look into making it public.

Yes, I've installed dependencies and compiled the app. I get the same results regardless.

Actually without building it I see no dependencies at all, when I build it I see only my app:

```
java-app  1.0-SNAPSHOT  java-archive
```

**Comment by rsareth** [comment] 2022-03-09 14:29
I'm facing the same issue. I have to run **mvn install** before and run the syft cli like this:

```shell
$ mvn install
$ syft packages dir:./target/dependencies
```

**Comment by luhring** [comment] 2022-03-25 12:56
@rsareth That's expected behavior today. Syft is looking for Java dependencies that _have been installed_, as opposed to dependencies that _will_ be installed.

My understanding from what @stefanm8 is saying is that there's also a scenario where Syft is not finding _installed_ Java dependencies — which is **not** expected behavior.

**Comment by luhring** [comment] 2022-05-21 15:30
Hi! Just checking in to see if there's a list of steps we could use to reproduce this on our end. If not, no worries, we can close this issue if it's not happening any more.

**Comment by spiffcs** [comment] 2022-05-25 22:01
@stefanm8 I was unable to reproduce this issue. Happy to reopen this later to keep discussing if it comes up again.

**Closed by spiffcs** 2022-05-25 22:01 UTC
Labels: bug, ecosystem:java
