### ISSUE TITLE
CycloneDX JSON is broken after 0.85.0 for Dependency Track

### ISSUE THREAD

**Issue by pentago** [anchore/syft#2070] opened 2023-08-28 09:47 UTC
**What happened**:

JSON BOMs created with syft binaries after 0.85.0 seem broken as DependencyTrack is unable to render data from these files. 0.85.0 is latest version that works with Dependency Track.

Uploaded ZIP with JSON files created with 0.85 and 0.88 binaries for  comparison.

[files.zip](https://github.com/anchore/syft/files/12453074/files.zip)

**What you expected to happen**:

Dependency track to display BOM data as it did up until 0.85.0.

**Steps to reproduce the issue**:

Run syft to scan the image and write outpout to a cyclonedx-json file, e.g. 
`syft --platform "linux/amd64" --output cyclonedx-json --file 0.88.0.json project.azurecr.io/project/xxx-image:20230822144646`

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
Application:        syft
Version:            0.88.0
JsonSchemaVersion:  10.0.1
BuildDate:          2023-08-25T20:45:04Z
GitCommit:          Homebrew
GitDescription:     [not provided]
Platform:           darwin/arm64
GoVersion:          go1.21.0
Compiler:           gc

- OS (e.g: `cat /etc/os-release` or similar):
MacOS Ventura 13.5 

Logs from Dependency Track when uploading BOM made with syft other than 0.85.0:

```
2023-08-23 12:30:23,800 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: ea10ab0a-6a08-4b8b-b9f8-8c5b8ff348e4
2023-08-23 12:30:25,598 WARN [Persist] Insert of object "org.dependencytrack.model.Component@7ca7f09c" using statement "INSERT INTO "COMPONENT" ("AUTHOR","BLAKE2B_256","BLAKE2B_384","BLAKE2B_512","BLAKE3","CLASSIFIER","COPYRIGHT","CPE","DESCRIPTION","DIRECT_DEPENDENCIES","EXTENSION","EXTERNAL_REFERENCES","FILENAME","GROUP","INTERNAL","LAST_RISKSCORE","LICENSE","LICENSE_URL","MD5","NAME","TEXT","PARENT_COMPONENT_ID","PROJECT_ID","PUBLISHER","PURL","PURLCOORDINATES","LICENSE_ID","SHA1","SHA_256","SHA_384","SHA3_256","SHA3_384","SHA3_512","SHA_512","SWIDTAGID","UUID","VERSION") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" failed : ERROR: null value in column "NAME" of relation "COMPONENT" violates not-null constraint
  Detail: Failing row contains (206431, null, null, null, null, LIBRARY, null, cpe:2.3:a:_:_:0.0.0.0:*:*:*:*:*:*:*, null, null, null, null, null, null, f, null, null, null, null, null, null, null, 151, null, pkg:nuget/%20@0.0.0.0, pkg:nuget/%20@0.0.0.0, null, null, null, null, null, null, null, null, null, 64439e2a-7297-487a-9128-195d495ed649, 0.0.0.0, null).
2023-08-23 12:30:25,599 ERROR [BomUploadProcessingTask] Error while processing bom
javax.jdo.JDODataStoreException: Insert of object "org.dependencytrack.model.Component@7ca7f09c" using statement "INSERT INTO "COMPONENT" ("AUTHOR","BLAKE2B_256","BLAKE2B_384","BLAKE2B_512","BLAKE3","CLASSIFIER","COPYRIGHT","CPE","DESCRIPTION","DIRECT_DEPENDENCIES","EXTENSION","EXTERNAL_REFERENCES","FILENAME","GROUP","INTERNAL","LAST_RISKSCORE","LICENSE","LICENSE_URL","MD5","NAME","TEXT","PARENT_COMPONENT_ID","PROJECT_ID","PUBLISHER","PURL","PURLCOORDINATES","LICENSE_ID","SHA1","SHA_256","SHA_384","SHA3_256","SHA3_384","SHA3_512","SHA_512","SWIDTAGID","UUID","VERSION") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" failed : ERROR: null value in column "NAME" of relation "COMPONENT" violates not-null constraint
  Detail: Failing row contains (206431, null, null, null, null, LIBRARY, null, cpe:2.3:a:_:_:0.0.0.0:*:*:*:*:*:*:*, null, null, null, null, null, null, f, null, null, null, null, null, null, null, 151, null, pkg:nuget/%20@0.0.0.0, pkg:nuget/%20@0.0.0.0, null, null, null, null, null, null, null, null, null, 64439e2a-7297-487a-9128-195d495ed649, 0.0.0.0, null).
        at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:605)
        at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:702)
        at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:722)
        at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:427)
        at org.dependencytrack.persistence.ComponentQueryManager.createComponent(ComponentQueryManager.java:306)
        at org.dependencytrack.persistence.QueryManager.createComponent(QueryManager.java:515)
        at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:206)
        at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:141)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "NAME" of relation "COMPONENT" violates not-null constraint
  Detail: Failing row contains (206431, null, null, null, null, LIBRARY, null, cpe:2.3:a:_:_:0.0.0.0:*:*:*:*:*:*:*, null, null, null, null, null, null, f, null, null, null, null, null, null, null, 151, null, pkg:nuget/%20@0.0.0.0, pkg:nuget/%20@0.0.0.0, null, null, null, null, null, null, null, null, null, 64439e2a-7297-487a-9128-195d495ed649, 0.0.0.0, null).
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:430)
        at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:520)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
        at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4587)
        at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4564)
        at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2014)
        at org.datanucleus.ExecutionContext.persistObjectInternal(ExecutionContext.java:320)
        at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1862)
        at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1723)
        at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:697)
        ... 10 common frames omitted
2023-08-23 12:30:25,600 WARN [Retrieve] Search for object with id "org.dependencytrack.model.Project:151" using statement "SELECT 1 FROM "PROJECT" "A0" WHERE "A0"."ID" = ?" failed : ERROR: current transaction is aborted, commands ignored until end of transaction block
2023-08-23 12:30:25,600 WARN [General] ExecutionContext closed with active transaction, so rolling back the active transaction
2023-08-23 12:30:25,601 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
javax.jdo.JDODataStoreException: Search for object with id "org.dependencytrack.model.Project:151" using statement "SELECT 1 FROM "PROJECT" "A0" WHERE "A0"."ID" = ?" failed : ERROR: current transaction is aborted, commands ignored until end of transaction block
        at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:605)
        at org.datanucleus.api.jdo.JDOPersistenceManager.getObjectById(JDOPersistenceManager.java:1726)
        at alpine.persistence.AbstractAlpineQueryManager.detach(AbstractAlpineQueryManager.java:498)
        at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:184)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.datanucleus.store.rdbms.SQLController.executeStatementQuery(SQLController.java:548)
        at org.datanucleus.store.rdbms.request.LocateRequest.execute(LocateRequest.java:270)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.locateObject(RDBMSPersistenceHandler.java:615)
        at org.datanucleus.state.StateManagerImpl.locate(StateManagerImpl.java:1278)
        at org.datanucleus.state.StateManagerImpl.validate(StateManagerImpl.java:5586)
        at org.datanucleus.ExecutionContextImpl.findObject(ExecutionContextImpl.java:3446)
        at org.datanucleus.ExecutionContextImpl.findObject(ExecutionContextImpl.java:2928)
        at org.datanucleus.api.jdo.JDOPersistenceManager.getObjectById(JDOPersistenceManager.java:1721)
        ... 6 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "NAME" of relation "COMPONENT" violates not-null constraint
  Detail: Failing row contains (206431, null, null, null, null, LIBRARY, null, cpe:2.3:a:_:_:0.0.0.0:*:*:*:*:*:*:*, null, null, null, null, null, null, f, null, null, null, null, null, null, null, 151, null, pkg:nuget/%20@0.0.0.0, pkg:nuget/%20@0.0.0.0, null, null, null, null, null, null, null, null, null, 64439e2a-7297-487a-9128-195d495ed649, 0.0.0.0, null).
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:430)
        at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:520)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
        at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4587)
        at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4564)
        at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2014)
        at org.datanucleus.ExecutionContext.persistObjectInternal(ExecutionContext.java:320)
        at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1862)
        at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1723)
        at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:697)
        at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:722)
        at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:427)
        at org.dependencytrack.persistence.ComponentQueryManager.createComponent(ComponentQueryManager.java:306)
        at org.dependencytrack.persistence.QueryManager.createComponent(QueryManager.java:515)
        at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:206)
        at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:141)
        ... 4 common frames omitted

```

**Comment by wagoodman** [comment] 2023-08-30 14:57
I was able to reproduce the issue, however, this appears to be a dependency track issue at first glance. I tried this same procedure out with v0.85.0, v0.86, v0.87.0, v0.87.1, and v0.88.0 of syft. 

I analyzed the `docker.io/anchore/test_images:grype-quality-node-d89207b@sha256:f56164678054e5eb59ab838367373a49df723b324617b1ba6de775749d7f91d4` image with, in this case, v0.87.1 and v0.88.0... here are the differences in the SBOMs:

```
diff node-87.1.cxd.json node-88.cxd.json
5c5
<   "serialNumber": "urn:uuid:6210eeda-b37d-41df-8fa8-4ad66be6b1c1",
---
>   "serialNumber": "urn:uuid:4eaba29c-fc81-4119-90f9-f833dbd73254",
8c8
<     "timestamp": "2023-08-30T10:15:20-04:00",
---
>     "timestamp": "2023-08-30T09:56:36-04:00",
13c13
<         "version": "0.87.1"
---
>         "version": "0.88.0"

```

It seems to be the second SBOM that is loaded will case the traceback, no matter what the version is. So, with a clean install of dependency track:
- create a new project, upload v0.87.1 cdx json : successful
- upload v0.88.0 cdx json: traceback ("syft-2070-dtrack-apiserver-1  | javax.jdo.JDOObjectNotFoundException: Object with id "org.dependencytrack.model.Component:365" not found !")
- upload v0.87.0 cdx json: successful
- upload v0.88.0 cdx json: successful

And again, with a clean install of dependency track:
- create a new project, upload v0.88 cdx json : successful
- upload v0.87.1 cdx json: traceback ("syft-2070-dtrack-apiserver-1  | javax.jdo.JDOObjectNotFoundException: Object with id "org.dependencytrack.model.Component:246" not found !")
- upload v0.88.0 cdx json: successful
- upload v0.87.1 cdx json: successful

Also note that the component number that the traceback is different each time, which is slight hint that this isn't really about the SBOM content itself since the SBOM content is stable between syft calls.

I'm going to close this issue for now, however, please feel free to open a new issue with additional details if you feel that I didn't quite interpret the same reproduction steps you were describing / I missed something.

**Closed by wagoodman** 2023-08-30 14:57 UTC
Labels: bug
