### ISSUE TITLE
Grype does not scan software not added by package manager

### ISSUE THREAD

**Issue by mkesper** [anchore/syft#994] opened 2022-05-10 15:45 UTC
**What happened**:

No java executable was found when scanning docker image eclipse-temurin:11.0.14_9-jre-alpine

**What you expected to happen**:

syft should recognize executables even [when added via tar](https://github.com/adoptium/containers/blob/5a7c9b25bbca1cde27828e819f765614f7daf774/11/jdk/alpine/Dockerfile.releases.full)

**How to reproduce it (as minimally and precisely as possible)**:

```
syft eclipse-temurin:11.0.14_9-jre-alpine -o syft-json=syft_sbom_eclipse-temurin.json
grep java syft_sbom_eclipse-temurin.json
   "type": "java-archive",
   "foundBy": "java-cataloger",
     "path": "/opt/java/openjdk/lib/jrt-fs.jar",
   "language": "java",
    "virtualPath": "/opt/java/openjdk/lib/jrt-fs.jar",

```
**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
Application:        syft
Version:            0.43.0
JsonSchemaVersion:  3.2.2
BuildDate:          2022-03-31T20:22:46Z
GitCommit:          f24bbc1838351e4e408368f3312c76db6552e71e
GitDescription:     v0.43.0
Platform:           linux/amd64
GoVersion:          go1.18
Compiler:           gc
- OS (e.g: `cat /etc/os-release` or similar):
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by luhring** [comment] 2022-05-21 16:06
Hi @mkesper! This might be a duplicate of #524, but let me know if I've misunderstood the intent of this issue.

**Comment by mkesper** [comment] 2022-05-27 06:30
I think besides #524, grype should list all executables / libs it could not track in a system package. Detecting everything correctly might not be possible but providing hints that there is something possibly dangerous in the image.

**Comment by tgerla** [comment] 2023-02-02 21:58
Hi @mkesper, sorry for the very long delay replying here. We have recently added some binary detection capabilities to Syft. Do you want to give this a try with the latest Syft and see if that solves your problem? Let us know how it goes. Thanks!

**Comment by tgerla** [comment] 2023-02-16 20:25
We'll go ahead and close this issue but please feel free to reopen it if you have more questions.

**Closed by tgerla** 2023-02-16 20:25 UTC
Labels: bug
