### ISSUE TITLE
Surface Rust dependency relationships

### ISSUE THREAD

**Issue by Dungeon1** [anchore/syft#2353] opened 2023-11-24 09:35 UTC
**What happened**:
Syft not created "dependencies" in cyclonedx report for Go, Rust, Java and etc.
Cargo.lock had "dependencies". View like

```
[[package]]
name = "yaserde"
version = "0.8.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "4bf52af554a50b866aaad63d7eabd6fca298db3dfe49afd50b7ba5a33dfa0582"
dependencies = [
 "log",
 "xml-rs",
 "yaserde_derive",
]
```
But output syft doesnt reflect this
**What you expected to happen**:
Want full cyclonedx report with "dependencies" and "depensOn" included

**Steps to reproduce the issue**:
syft -o cyclone-dx-json@1.5 Cargo.lock > report.json

**Anything else we need to know?**:

**Environment**:
Syft 0.94

**Comment by tgerla** [comment] 2023-11-27 18:56
Hi @Dungeon1, thanks for the report. I can confirm that the dependencies show up in the syft-json format output, but not the cyclonedx-json or cyclonedx-xml output. I will confirm with the team if this is expected behavior or not and get back to when we are able to look. Thanks again.

**Comment by Dungeon1** [comment] 2023-12-14 13:49
@wagoodman  I ran on Cargo.lock like your example.

**Comment by Dungeon1** [comment] 2023-12-14 13:50
Cargo.lock had dependencies, but syft not building dependencies with dependsOn.

**Comment by willmurphyscode** [comment] 2024-01-03 10:29
I was also able reproduce this. It looks like syft is detecting the dependencies (because they show up in `o json`), but isn't writing them down in cyclonedx-json. Moving to the backlog, thanks for the report!

**Closed** 2024-11-14 21:45 UTC
Labels: enhancement, ecosystem:rust
