### ISSUE TITLE
Support fetching packaging information from build tooling

### ISSUE THREAD

**Issue by wagoodman** [anchore/syft#1736] opened 2023-04-13 13:44 UTC
_(this has been a topic going around for a while between many folks, so I wanted to raise it up as an issue explicitly... I don't think I saw an existing issue for this, which was a little surprising)_

**What would you like to be added**:
Allow for querying ecosystem build tooling for populating package information.

For example, today we have a `go-mod-file-cataloger` which parses the go.mod file and raises up what is found. There are limitations of what can be found with this method, such as full transitive dependencies. Though some later go.mod files list out all transitive dependencies, the connectivity graph between all dependencies is lost. This connectivity can be discovered with the `go` tooling directly (e.g. `go mod graph`, `go list -deps`, etc.) and used to populate the SBOM.

**Why is this needed**:
In order to achieve https://github.com/anchore/syft/issues/1674 and https://github.com/anchore/syft/issues/572 in a meaningful way we should be able to query `go` directly (e.g. `go mod graph`, `go list -deps`, etc.) to populate the SBOM.

**Additional context**:
This functionality should be opt-in, that is, by default syft should remain a static analysis tool. Executing other commands on the system should still be not allowed by default (again, unless the user opts in).

Considerations:
- should these "external querying capabilities" be encapsulated into their own separate catalogers? For example `go-mod-file-cataloger` stays as it is today and allow for a new `go-tooling-cataloger`. In this way opting in would be adding a cataloger (or enabling a flag which would automatically swap out one cataloger for another).
- we probably don't want to find duplicate packages by doing a static analysis and tooling query, there should be an obvious mechanism for enforcing mutual exclusivity for existing (static) analysis and tooling analysis.
- even if a new cataloger is not used to encapsulate this behavior it should be obvious to the user that this was found via a tooling query vs looking at just the go.mod contents (more than just the application configuration probably)

**Comment by kzantow** [comment] 2023-04-13 16:41
Similar to, and possible duplicate of: https://github.com/anchore/syft/issues/1562

**Comment by wagoodman** [comment] 2023-04-13 17:00
yup, good find! I'll close this and make any more comments there.

**Closed** 2023-04-13 17:01 UTC
Labels: enhancement
