### ISSUE TITLE
Syft does not generate valid SPDX documents

### ISSUE THREAD

**Issue by rnjudge** [anchore/syft#1401] opened 2022-12-13 23:28 UTC
**Please provide a set of steps on how to reproduce the issue**
When I ran Syft on three minimal container base images (`photon:3.0`, `debian:latest` and `alpine:latest`), none of the output from Syft validated in tag-value or json output (using https://tools.spdx.org/app/validate/ to validate).

**What happened**:
Errors seen when validating the JSON output include:

```
[instance type (null) does not match any allowed primitive type 
(allowed: ["array"]) for {"pointer":"/files/<*0..n*>/checksums"}

Document must have at least one relationship of type DOCUMENT_DESCRIBES]
```

Errors seen for tag-value documents include:

```
[Package at line 25461 invalid: Warning: Found analyzed files for package libc-bin when analyzedFiles is set to false.,
Package at line 25461 invalid: Missing required SHA1 hashcode value for <insert_filename_here>
```

**What you expected to happen**:
SPDX documents generatd by Syft should be valid SPDX documents.

**Comment by kzantow** [comment] 2022-12-14 00:06
I'm pretty sure this is a duplicate of: https://github.com/anchore/syft/issues/1396 -- please reopen if it's not!

**Comment by rnjudge** [comment] 2022-12-14 15:38
This issue includes more than just the files analyzed issue mentioned in #1396. It also includes issues with the formatting of the JSON format and missing fields in the JSON format.

**Comment by rnjudge** [comment] 2022-12-14 15:39
I'm not able to re-open this issue.. but I think it should remain open :)

**Comment by kzantow** [comment] 2022-12-14 17:43
Reopening this for the `null` array issue.

**Comment by spiffcs** [comment] 2022-12-19 18:53
@rnjudge if you want to check out #1404 I've added a path that generates valid SPDX documents for the images you listed

**Comment by spiffcs** [comment] 2022-12-20 20:57
https://github.com/spdx/tools-golang/pull/176 <-- This issue is blocked until this is merged upstream with the correct field for the tools-golang library

**Comment by spiffcs** [comment] 2022-12-21 15:20
After https://github.com/anchore/syft/pull/1418 is merged you should have success generating VALID spdx using the commands from the PR.

The digest cataloger that produces sha1s for regular files is not currently default syft behavior, but can be enabled with the following env:
```
SYFT_FILE_METADATA_CATALOGER_ENABLED=true SYFT_FILE_METADATA_DIGESTS=sha1 
```

**Closed** 2022-12-21 20:56 UTC
Labels: bug, duplicate, blocked
