### ISSUE TITLE
On a purl a name must be a percent-encoded string

### ISSUE THREAD

**Issue by thorin** [anchore/syft#351] opened 2021-03-23 17:16 UTC
**What happened**:
The package name of the components on the purl are not percent encoded.

**What you expected to happen**:
According to the purl spec: https://github.com/package-url/purl-spec

>    The name is prefixed by a '/' separator when the namespace is not empty
>    This '/' is not part of the name
>    A name must be a percent-encoded string

**How to reproduce it (as minimally and precisely as possible)**:

This can be check on a container image with g++ installed:
```
    <component type="library">
      <name>g++</name>
      <version>4:8.3.0-1</version>
      <purl>pkg:deb/debian/g++@4:8.3.0-1?arch=amd64</purl>
    </component>
```

**Environment**:
- Output of `syft version`:
```
Application:   syft
Version:       0.14.0
BuildDate:     2021-03-20T16:47:03Z
GitCommit:     26a4dd36a8932c7867fcdd6296f50643be30f8a6
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.14.15
Compiler:      gc
```

**Comment by luhring** [comment] 2021-04-15 18:25
@thorin Good catch!

**Adding my steps to reproduce:**

- I used this Dockerfile:

```Dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y g++
```

- I built the image using:
`docker built -t test:latest .`

- I looked at Syft's reported purl for `g++` using (with Syft v0.14.0): 
`syft test:latest -o json | jq '.artifacts[] | select(.name == "g++") | {name, purl}'`

And I get this:
```json
{
  "name": "g++",
  "purl": "pkg:deb/ubuntu/g++@4:9.3.0-1ubuntu2?arch=amd64"
}
```

And it looks like the spec is saying the `g++` should have been `g%2B%2B`.

**Comment by kzantow** [comment] 2021-08-12 17:48
NOTE: it looks like this is fixed in a stalled PR: https://github.com/package-url/packageurl-go

**Comment by kzantow** [comment] 2021-08-13 14:34
I've had to dig a bit deeper into this issue. As it stands, the [packageurl-go](https://github.com/anchore/packageurl-go) library (including the PR that might have changed this) is not encoding the `+` character, as it is using Go's `url.PathEscape`. I had to read through the spec, and to me there's still possibly a bit of ambiguity, but I think it is actually the correct behavior to include the `+` character, specifically.

The purl spec section on [Character Encoding](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst#character-encoding) where it defines "percent-encoding" says, in effect: _separator characters and non-ascii characters must be encoded_. But, the `+` is an ascii character and it is not a separator character, thus shouldn't be percent-encoded.

I've created a PR that includes a minor fix to the library for encoding, as well as adding a few more tests for encoding cases here: https://github.com/anchore/syft/pull/481

Is this causing an issue for you, otherwise @thorin?

**Comment by thorin** [comment] 2021-08-15 21:57
@kzantow give me a couple of days to test. 

If you are correct then the problem will be in the parser I'll need to open a bug report there.

**Comment by thorin** [comment] 2021-09-02 19:59
Feel free to close this @kzantow. This will be fixed on the parser side.

Thank you

**Comment by kzantow** [comment] 2021-09-02 20:47
Thanks for following up, @thorin !

**Closed by kzantow** 2021-09-02 20:47 UTC
Labels: bug, good first issue
