### ISSUE TITLE
SHA-256 mismatch when installing via Homebrew

### ISSUE THREAD

**Issue by jscheid** [anchore/syft#886] opened 2022-03-13 20:44 UTC
**What happened**:

```
$ brew upgrade
==> Upgrading 8 outdated packages:
(SNIP)
anchore/syft/syft 0.41.1 -> 0.41.4
(SNIP)
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/262126497/d8fd0f61-34a7-4104-a37e-4d947db99664?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=(SNIP)
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 422f55c61eff1eefa0c2b4e0341dec1d57ee8a2f82de59225a899bbcc12b698d
  Actual: 2a2e5001172f8af07368f8fc44e19e0ae3c304bdf93f7f487b84c6ff7a2cabda
    File: /Users/myuser/Library/Caches/Homebrew/downloads/6194c42cdc864651a5737011bc0e5fe160a0a1a827906c807119f009bacb13a4--syft_0.41.4_darwin_amd64.tar.gz
```

**What you expected to happen**:

N/A

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**:

I've already tried reinstalling from scratch using 

```
brew cleanup
rm ~/Library/Caches/Homebrew/downloads/6194c42cdc864651a5737011bc0e5fe160a0a1a827906c807119f009bacb13a4--syft_0.41.4_darwin_amd64.tar.gz
brew update
brew upgrade
```

After removing the `syft` package, other packages install fine.

**Environment**:
- Output of `syft version`: N/A
- OS (e.g: `cat /etc/os-release` or similar): macOS 10.15.7 (19H1715)

```
$ brew --version
Homebrew 3.4.1-52-gf0f1eb6
Homebrew/homebrew-core (git revision 8822fe47f4e; last commit 2022-03-13)
Homebrew/homebrew-cask (git revision 96b4f7dabd; last commit 2022-03-14)
```

**Comment by luhring** [comment] 2022-03-25 12:43
Hi @jscheid — just checking, are you still experiencing this? I believe this is resolved at this point

**Comment by wagoodman** [comment] 2022-04-26 16:11
@jscheid closing this for now since we think it's solved, please reopen if you think otherwise!

**Closed by wagoodman** 2022-04-26 16:11 UTC
Labels: bug, changelog-ignore

**Comment by Subomi-olagoke** [comment] 2022-10-15 11:22
Hello! I am reopening this to let you know that the issue is not yet solved :)

**Comment by kzantow** [comment] 2022-10-17 13:05
@Subomi-olagoke -- I just tried this on both Intel Mac and M1 Mac without issue -- are you still having this problem?

**Comment by Subomi-olagoke** [comment] 2022-10-17 13:58
Yes , I am , I am running it on an intel based Mac and have tried uninstalling and reinstalling homebrew multiple times , but nothing changed On Oct 17, 2022, at 2:06 PM, Keith Zantow ***@***.***> wrote:﻿
@Subomi-olagoke -- I just tried this on both Intel Mac and M1 Mac without issue -- are you still having this problem?

**Comment by kzantow** [comment] 2022-10-17 14:10
@Subomi-olagoke you noted uninstalling and reinstalling homebrew, but have you tried:
```
brew remove syft
brew install syft
```
?

**Comment by Subomi-olagoke** [comment] 2022-10-17 14:45
No , I haven’t , I’ll try that and give you a feedback ,  sorry On Oct 17, 2022, at 3:10 PM, Keith Zantow ***@***.***> wrote:﻿
@Subomi-olagoke you noted uninstalling and reinstalling homebrew, but have you tried:
brew remove syft
brew install syft

?

**Comment by wulph111** [comment] 2022-12-03 23:54
> I’ll try that and give you a feedback

any feeback?
