### ISSUE TITLE
javascript-lock-cataloger not detect and parse yarn.lock file

### ISSUE THREAD

**Issue by ansidorov** [anchore/syft#798] opened 2022-02-07 14:10 UTC
**What happened**: Syft javascript-lock-cataloger not detect and parse yarn.lock file

**What you expected to happen**: Syft must to generate SBOM for yarn.lock file

**How to reproduce it (as minimally and precisely as possible)**:
```
docker run --rm -ti ubuntu:20.04 bash
docker# apt update; apt install -y curl git
docker# git clone https://github.com/belgattitude/nextjs-monorepo-example.git
docker# cd nextjs-monorepo-example
docker# curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
docker# syft -vv packages dir:$(pwd)
[0000] DEBUG application config:
output:
- table
file: ""
quiet: false
check-for-app-update: true
anchore:
  host: ""
  path: ""
  dockerfile: ""
  overwrite-existing-image: false
  import-timeout: 30
dev:
  profile-cpu: false
  profile-mem: false
log:
  structured: false
  level: debug
  file: ""
package:
  cataloger:
    enabled: true
    scope: Squashed
  search-unindexed-archives: false
  search-indexed-archives: true
file-metadata:
  cataloger:
    enabled: false
    scope: Squashed
  digests:
  - sha256
file-classification:
  cataloger:
    enabled: false
    scope: Squashed
file-contents:
  cataloger:
    enabled: false
    scope: Squashed
  skip-files-above-size: 1048576
  globs: []
secrets:
  cataloger:
    enabled: false
    scope: AllLayers
  additional-patterns: {}
  exclude-pattern-names: []
  reveal-values: false
  skip-files-above-size: 1048576
registry:
  insecure-skip-tls-verify: false
  insecure-use-http: false
  auth: []
exclude: []

[0000] DEBUG checking if new vesion of syft is available
[0000] DEBUG no new syft update available
[0000]  INFO syft version: 0.36.0
[0000] DEBUG   ├── buildDate: 2022-01-19T20:25:30Z
[0000] DEBUG   ├── compiler: gc
[0000] DEBUG   ├── gitCommit: aebe843c6f0307d5c263c25257caf3e6ea827c78
[0000] DEBUG   ├── gitTreeState: clean
[0000] DEBUG   ├── goVersion: go1.16.13
[0000] DEBUG   ├── platform: linux/amd64
[0000] DEBUG   └── version: 0.36.0
[0000] DEBUG indexing filesystem path="/nextjs-monorepo-example"
[0000] DEBUG indexing filesystem path="/nextjs-monorepo-example/static/assets"
[0000]  INFO could not identify distro
[0000]  INFO cataloging directory
[0000] DEBUG cataloging with "ruby-gemfile-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "python-index-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "python-package-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "php-composer-lock-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "javascript-lock-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "dpkgdb-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "rpmdb-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "java-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "apkdb-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "go-module-binary-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "go-mod-file-cataloger"
[0000] DEBUG discovered 0 packages
[0000] DEBUG cataloging with "rust-cataloger"
[0000] DEBUG discovered 0 packages
No packages discovered
```

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 
```
Application:   syft
Version:       0.36.0
BuildDate:     2022-01-19T20:25:30Z
GitCommit:     aebe843c6f0307d5c263c25257caf3e6ea827c78
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.16.13
Compiler:      gc
```
- OS (e.g: `cat /etc/os-release` or similar):
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by luhring** [comment] 2022-05-21 15:12
Hi @ansidorov, I just ran through the repro steps, and I'm seeing several packages reported from `yarn.lock`.

Using your steps as a guide, I saved the Syft output and then analyzed it using `jq`:

```console
$ apt-get install -y jq
$ syft . -q -o json > ./sbom.json
$ cat ./sbom.json | jq '.artifacts | map(select(.locations | first | select(.path == "yarn.lock"))) | length'
2214
```

Could you try again with the [latest release of Syft](https://github.com/anchore/syft/releases) and let us know if you're still seeing this issue?

**Comment by tgerla** [comment] 2022-08-04 17:28
Hi @ansidorov, we are going to close this issue, but if the problem is still affecting you, please re-open or open a new issue and we will take another look. Thank you!

**Closed by tgerla** 2022-08-04 17:28 UTC
Labels: bug
