### ISSUE TITLE
podman report not working

### ISSUE THREAD

**Issue by pashok2398** [anchore/syft#893] opened 2022-03-16 20:50 UTC
**What happened**:
Fedora35
```
$ syft podman:docker.io/library/postgres:11

1 error occurred:
	* failed to construct source from user input "podman:docker.io/library/postgres:11": could not fetch image "docker.io/library/postgres:11": no host address


$ syft podman:postgres:11

1 error occurred:
	* failed to construct source from user input "podman:postgres:11": could not fetch image "postgres:11": no host address
```
RHCOS (OCP)
```
$ syft podman:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bb5f32d6a5294d211e7016a3aeefc1a02dd8ce3773747bcead61ab40f3a13366

1 error occurred:
	* failed to construct source from user input "podman:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bb5f32d6a5294d211e7016a3aeefc1a02dd8ce3773747bcead61ab40f3a13366": could not fetch image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bb5f32d6a5294d211e7016a3aeefc1a02dd8ce3773747bcead61ab40f3a13366": no host address
```

**What you expected to happen**:
That syft will generate report

**How to reproduce it (as minimally and precisely as possible)**:
Run the above commands

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
- 
```
$ syft version
Application:        syft
Version:            0.41.6
JsonSchemaVersion:  3.1.0
BuildDate:          2022-03-16T15:08:23Z
GitCommit:          ee0a1d172c0c6f0da907694b9b48870b33d2852d
GitDescription:     v0.41.6
Platform:           linux/amd64
GoVersion:          go1.17.7
Compiler:           gc
```
- OS (e.g: `cat /etc/os-release` or similar):

**F35**
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 35 (Thirty Five)
Release:	35
Codename:	ThirtyFive
```

**RHCOS**
```
$ cat  /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="49.84.202201042103-0"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION_ID="4.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 49.84.202201042103-0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.9"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.9"
OPENSHIFT_VERSION="4.9"
RHEL_VERSION="8.4"
OSTREE_VERSION='49.84.202201042103-0'
```
Thanks

**Comment by jonasagx** [comment] 2022-03-17 01:05
Thanks for reporting this issue, @pashok2398 -- the error returned by syft could give more information, I apologize for that:
> failed to construct source from user input "podman:docker.io/library/postgres:11": could not fetch image "docker.io/library/postgres:11": no host address 

I suspect the root cause is syft can't locate Podman's configuration file or environment variables. Do you have Podman installed?

> "podman:quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bb5f32d6a5294d211e7016a3aeefc1a02dd8ce3773747bcead61ab40f3a13366": could not fetch image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bb5f32d6a5294d211e7016a3aeefc1a02dd8ce3773747bcead61ab40f3a13366": no host address

Same problem here. I looked this image up and my access was forbidden. Once you have podman running locally, you probably need to set your credentials to access that image, more info [here](https://docs.podman.io/en/latest/markdown/podman-login.1.html).

**Comment by pashok2398** [comment] 2022-03-20 11:12
Hi @jonasagx 
Thanks for looking into it.
Yes i h ave podman installed, i am inside RHCOS
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux CoreOS release 4.9
```
```
$ podman version
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.7
Built:        Thu Jul 29 15:02:43 2021
OS/Arch:      linux/amd64
```

I just check on my F35 with podman and have the same issue
```
$ cat /etc/redhat-release                                                                                                                                                                                                    
Fedora release 35 (Thirty Five)
```
```
$ podman version                                                     
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 23:45:07 2021
OS/Arch:      linux/amd64
```

  ```
$ podman images |grep docker.io/library/postgres     
docker.io/library/postgres                                  11          a1377d9ce157  2 days ago     292 MB
docker.io/library/postgres                                  latest      07e2ee723e2d  2 months ago   382 MB
```
```
 $ podman run -it --rm --entrypoint bash docker.io/library/postgres:11
root@fc0e9ef7762a:/# whoami
root
root@fc0e9ef7762a:/# exit
```

```
$ syft podman:docker.io/library/postgres:11                                    
1 error occurred:
	* failed to construct source from user input "podman:docker.io/library/postgres:11": could not fetch image "docker.io/library/postgres:11": no host address
```

```
$ syft podman:postgres:11        

1 error occurred:
	* failed to construct source from user input "podman:postgres:11": could not fetch image "postgres:11": no host address
```


```
$ podman version                                                     
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 23:45:07 2021
OS/Arch:      linux/amd64
```


Regarding the permissions issue, you getting this because its RH private repo i am able to pull and have this image as i am running on OCP and its in my image list.

**Comment by jonasagx** [comment] 2022-03-22 00:53
I've reproduced your error (by running fedora over podman). The problem is Podman is not running as a daemon. You can check its status via: `systemctl status podman.socket`. Syft requires Podman's daemon to pull images.
If you'd rather use Syft without a daemon service (either podman or docker) you can simply run `syft postgres:11` and Syft will use its own OCI client.

An example of how to start Podman's daemon is in our CI system:
https://github.com/anchore/stereoscope/blob/main/.github/workflows/validations.yaml#L111-L122

The steps look like this:
```sh
loginctl enable-linger $(whoami)
sleep 5
export XDG_RUNTIME_DIR=/run/user/$UID
mkdir -p $HOME/.config/systemd/user
systemctl --user enable --now podman.socket
sudo systemctl start podman.socket
```

FYI: you can see syft's debug logs this way:
```sh
syft postgres:11 -vv
```

I am working on a better error message for situations like that.

**Comment by jonasagx** [comment] 2022-03-22 21:22
@pashok2398 could you provide more details of why it is not working with `root`? Debug logs can provide more information, if you can share them.

Podman and Docker keep copies of their images locally, using one of them will let you scan a local image. If also have these options for local scanning:
```sh
syft docker-archive:path/to/yourimage.tar   #use a tarball from disk for archives created from "docker save"
syft oci-archive:path/to/yourimage.tar      #use a tarball from disk for OCI archives (from Skopeo or otherwise)
syft oci-dir:path/to/yourimage              #read directly from a path on disk for OCI layout directories (from Skop
```

**Comment by pashok2398** [comment] 2022-03-22 22:51
@jonasagx I am not sure but looks like podman with root running without the podman.sock....
```
ll /run/podman/
total 0
```
However i think i found a solution...
I am scanning the overlay dir (`merged`) for each running container....
```
syft -q --output json dir:/var/lib/containers/storage/overlay/721d1f2fb66ffd8d7939874bf15713ea0007167af48c8d4afdffb4e088fc8513/merged
```

What do you think? can i miss something using this way of scan?

**Comment by jonasagx** [comment] 2022-03-24 23:42
Hey @pashok2398 I will try to reproduce your issue with root user, how did you install podman?

By [docker docs](https://docs.docker.com/storage/storagedriver/overlayfs-driver/):
> The merged directory is the union mount of the lowerdir and upperdir, which comprises the view of the filesystem from within the running container.

Your syft command above is equivalent to: `podman run -it my/image:latest syft /` where you run syft inside the container. You should capture all that is available to the container. The performance will suffer with slow syscalls to open files and index them.

**Comment by tgerla** [comment] 2022-08-04 17:33
Hi @pashok2398, we are going to go ahead and close this issue since it has been a few months since we received a reply. But if you are still having trouble, please re-open it or file a new issue with any additional details you have, and we will help you out. Thank you!

**Closed by tgerla** 2022-08-04 17:33 UTC
Labels: bug
