### ISSUE TITLE
Is recursively scan supported?

### ISSUE THREAD

**Issue by evanchaoli** [anchore/syft#1806] opened 2023-05-09 22:32 UTC
**What would you like to be added**:

When `syft` scans a tar file (or a zip file or so), if the tar file has inner tars, will inner tar file be recursively scanned?

My test with the simplest usage: `syft my.tar` didn't scan inner tar files, but I wonder if there is any magic to do so?

**Why is this needed**:

**Additional context**:

**Comment by tgerla** [comment] 2023-05-10 11:45
Hi @evanchaoli, we don't recursively scan inside archives, but we have discussed this idea in another issue: https://github.com/anchore/syft/issues/1379 -- if it's OK with you I'll close this issue as a duplicate of the other one, and feel free to weigh in over there! Thanks.

**Closed by tgerla** 2023-05-10 11:45 UTC
Labels: enhancement
