### ISSUE TITLE
Config file in scanned project conflicts with Syft config file.

### ISSUE THREAD

**Issue by bmanuel1974** [anchore/syft#659] opened 2021-12-09 16:59 UTC
**What happened**:
java jar builds fail to scan because the project being built has a file called **config.properties** with the following properties:
```
log.level=INFO
log.level.app=INFO
log.level.admin=INFO
```

Syft is failing to parse this file because the name conflicts with the Syft config file.

**What you expected to happen**:
Syft should use a more "private" name for the config file instead of "config".  This is a fairly popular name for an application to use.  I would suggest something like "_syft.config.properties" or "_syft.config.yaml" to lower/remove the chance for a project build to fail.  

**How to reproduce it (as minimally and precisely as possible)**:
Compile a java jar project and run Syft on the compiled results with a file called "config.properties" in the root of the resources folder.  The properties file should contain:
log.level.app=INFO
log.level.admin=INFO

**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
Application:   syft
Version:       0.32.0
BuildDate:     2021-12-08T21:46:11Z
GitCommit:     da0b17b719b6d5cabe0819d44f90755c73312de8
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.16.10
Compiler:      gc

- OS (e.g: `cat /etc/os-release` or similar):
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"

**Comment by luhring** [comment] 2021-12-23 13:56
Hi @bmanuel1974, can you share the error that Syft is outputting in this scenario? And do you have an example project we can look at to reproduce this?

Syft looks at the following locations to find its own config (see our [docs](https://github.com/anchore/syft#configuration)):


- `.syft.yaml`
- `.syft/config.yaml`
- `~/.syft.yaml`
- `<XDG_CONFIG_HOME>/syft/config.yaml`

All of these options have `syft` somewhere in the file path. Is that what you're referring to?

**Comment by spiffcs** [comment] 2022-07-13 18:22
Looks like this conflict does not exist @bmanuel1974. I tried to get it to reproduce and had all successful paths load a config. If this closed in error let me know otherwise I'll consider syft's configs private enough for the time being.

**Closed by spiffcs** 2022-07-13 18:22 UTC
Labels: bug
