### ISSUE TITLE
Syft report in my image is not being completed with default scope value

### ISSUE THREAD

**Issue by Galactic21** [anchore/syft#2104] opened 2023-09-07 10:05 UTC
Good morning, I'm using syft to create package reports in my gophish image. 
What is happening is that using the --scope all-layers flag it shows me packages with the old versions of those it has on the system. Therefore I chose to use the default (squashed). 
The bug I found ,at least in this image, is that the report is incomplete. For some reason that I can't explain, the report usually has 900000 lines and syft just doing around 340000 to 350000 lines to make the report.

I'm using the latest version of syft and I'm running this command to generate the report.

`ocker run --rm --volume /var/run/docker.sock:/var/run/docker.sock --name Syft anchore/syft:v0.89.0 phishing-gophish-o syft-json -vv  > syft_report.json`

If anyone could help me or indicate a flag or environment variable that would correct this, I would greatly appreciate it.

Cheers.

**Comment by kzantow** [comment] 2023-09-07 11:39
As written, there are a couple issues with the command you provided. I assume you meant this?
```
docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock --name Syft anchore/syft:v0.89.0 phishing-gophish -o syft-json -vv  > syft_report.json
```
Unfortunately I can't seem to pull `phishing-gophish` to test this out. You noted that the Syft JSON is "normally 900000 lines" but now is about 350000 lines -- do you have an idea what the differences are? One thing Syft does now is to remove binary entries when there is a corresponding package manager entry that matches, which would reduce the size a bit, but I wouldn't expect to account for more than half the entries...

**Comment by Galactic21** [comment] 2023-09-07 12:01
Yes, that's exactly the command.

![image](https://github.com/anchore/syft/assets/32776046/1d5c775f-f15e-4904-be0a-82d2f68b6578)

Yes, that's exactly the command.

As you can see in the image we have 2 reports, the first with an image that I have from another service (this one has fewer lines because at the top when it said 900000 it would be with the --scope all-layers flag active) and on the right with the image described above and he gave me the report along those lines I said previously. (with the --scope squashed flag)

**Comment by kzantow** [comment] 2023-09-07 12:24
Thanks @Galactic21 -- this is odd, indeed! From the screenshot, it looks like the SBOM is cut off mid-writing. Did you get any errors? Are there any publicly available images that you know of that exhibit this behavior?

**Comment by Galactic21** [comment] 2023-09-07 13:45
`[0000]  INFO syft version: 0.89.0
[0000] DEBUG config:
  log:
      quiet: false
      level: debug
      file: ""
  dev:
      profile: none
  config: ""
  output:
      - syft-json
  file: ""
  output-template-path: ""
  check-for-app-update: true
  catalogers: []
  package:
      cataloger:
          enabled: true
          scope: Squashed
      search-unindexed-archives: true
      search-indexed-archives: true
  golang:
      search-local-mod-cache-licenses: false
      local-mod-cache-dir: ""
      search-remote-licenses: false
      proxy: ""
      no-proxy: ""
  linux-kernel:
      catalog-modules: true
  python:
      guess-unpinned-requirements: false
  file-metadata:
      cataloger:
          enabled: false
          scope: Squashed
      digests:
          - sha256
  file-classification:
      cataloger:
          enabled: false
          scope: Squashed
  file-contents:
      cataloger:
          enabled: false
          scope: Squashed
      skip-files-above-size: 3000000
      globs: []
  secrets:
      cataloger:
          enabled: false
          scope: AllLayers
      additional-patterns: {}
      exclude-pattern-names: []
      reveal-values: false
      skip-files-above-size: 1048576
  registry:
      insecure-skip-tls-verify: false
      insecure-use-http: false
      auth: []
      ca-cert: ""
  exclude: []
  platform: ""
  name: ""
  source:
      name: ""
      version: ""
      file:
          digests:
              - sha256
  parallelism: 1
  default-image-pull-source: ""
  base-path: ""
  exclude-binary-overlap-by-ownership: true
[0000] DEBUG checking if a new version of syft is available
[0000] DEBUG no new syft update available
[0000] DEBUG image: source=DockerDaemon location=phishing-gophish
[0052] DEBUG image metadata: digest=sha256:c8ccb667cf3c93f31949586d80ce4677c062d334b10fd4cbc99be85a6ac2832e mediaType=application/vnd.docker.distribution.manifest.v2+json tags=[phishing-gophish:latest]
[0052] DEBUG layer metadata: index=0 digest=sha256:7f5cbd8cc787c8d628630756bcc7240e6c96b876c2882e6fc980a8b60cdfa274 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0052] DEBUG layer metadata: index=1 digest=sha256:31ee2011b35056e3f2d13588f0339c10cc52aa3aa012115a898f3c0f2f2cea12 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0052] DEBUG layer metadata: index=2 digest=sha256:bcb7e1bba665108211179067843fd5669a615985876d714fe6b514623f0646f3 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0053] DEBUG layer metadata: index=3 digest=sha256:93317e79c4049aab8ea725f3d75984d1cee7bdeb5f1746d1de15077b0311e7f4 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0054] DEBUG layer metadata: index=4 digest=sha256:05d020b31263227568464cba4590858ac897379b5ae5531950316bd56087729d mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0055] DEBUG layer metadata: index=5 digest=sha256:0049a9ed8e6b26226a96c24ba01980f70e1e76d47f991ab891efce622f4bd744 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0055] DEBUG layer metadata: index=6 digest=sha256:cc8c3b8b782678c7417c925c24f4441dfeb6d787c90fb89c5d25373f9fa1377e mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0056] DEBUG layer metadata: index=7 digest=sha256:905b02a59b74ee3a20c22f805a30e316b656e68930386f4382d4637f133619da mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0056] DEBUG layer metadata: index=8 digest=sha256:9c6b97c58da92427f830bf74f22b04882d1df29d481597f842f3bb227d011c81 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0056] DEBUG layer metadata: index=9 digest=sha256:94676b34dc35ddf33835acaffc0e47fab26aba6467f5a05981b18efe91ce83b1 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0056] DEBUG layer metadata: index=10 digest=sha256:e4ac63784cb88e3cd6beb50c6865296770b2ffe4c0aa8411d3e228ccfb243ced mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0056] DEBUG layer metadata: index=11 digest=sha256:00a6f45cf5cfd1773af714a67ce55b7c067513e038fe6932c33319f18a8a9555 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0056] DEBUG layer metadata: index=12 digest=sha256:2c3737f58a881455e6b2af93e645971f59d1aa4b4575907b269111907d4f1265 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0058] DEBUG layer metadata: index=13 digest=sha256:8c283b52600e9ac5dadf5b387bdd3897a0e8b1bc65cdf1b7d73afb7971a88a63 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0058] DEBUG layer metadata: index=14 digest=sha256:3be81150bef92d8d67b6aac7e4083316eb51f52b66b1e9dda3dc39cdff2eb3c9 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=15 digest=sha256:1561ed6f5e415f8278621f9697abf2db0bcd9eb8f21298f9c24b0dae9be5d109 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=16 digest=sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=17 digest=sha256:9bfde9142e60f3dbb683ae3b335163db77f615bf96914e86ffc90d54e7150a7d mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=18 digest=sha256:1beed3f9ed85ac9089bd192448be68b7a2b698214d4dde43a576677592c78234 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=19 digest=sha256:bb82dbf7298f6bb8377c6b98e0bffd8ae2001c1b1075c0d5472c3174719ba223 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=20 digest=sha256:51ad409c4d035c279d47592792a32f5cd4b2b7390a4a55c6bec98d0540a807a5 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=21 digest=sha256:191df87e49251dcb8cb76627f202e5ad33ec3cc6edca5feda88c79687e17e782 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=22 digest=sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=23 digest=sha256:c77627da7d04ff770ca2374a5b5f58dcf9ded021ad277a9abea1b625b1480118 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=24 digest=sha256:c77627da7d04ff770ca2374a5b5f58dcf9ded021ad277a9abea1b625b1480118 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=25 digest=sha256:fb0b29c4a47e273f2cbaf330d71e793df4642ccbe39c1635c198e3a838c022c7 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=26 digest=sha256:11507b1630b937be6de3f7b169e19e7f7e33e41dfafffdd32a7dfeb2cd72acf8 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=27 digest=sha256:f4a663d1a289ae866a896957553d8188ad6eaf1c05603be974ea761c701af673 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=28 digest=sha256:0466f9f6379d7fe44c2dda6fb1bc0cacfc5aa7d551a1273714a97d9f303ee651 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=29 digest=sha256:619477d680ebb189cd0d6d8fea39d29ea535cca00d477e36e253d2032643350f mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=30 digest=sha256:1f14e94eba5bae93a942636abea58c4e58c24d2a1ca672b4486d04526a9ee82f mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=31 digest=sha256:db6ea10c3295357b57edf564a50ce498d187899955acf888dffb76f3c83899b4 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=32 digest=sha256:b794d4045f4cdab3d001c34db2f6027ff1fa71b78fba6c0f63243737cd45422e mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=33 digest=sha256:b0247d67bba3e183a0525a593b2693e0d3ad21e3facfa8d563201954c9bee1a6 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=34 digest=sha256:c742a54299dfd7328be8d9b65cfe52e6eec931ecd20bece97f5bfe26fb73e86c mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=35 digest=sha256:15498df0d89a6385fd306ce3e9945f2c0728e46b8c80d0a0f20890be175e6781 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=36 digest=sha256:bdf40e499316ee690daff349907f93654d54467fa94573e39ae70ff1c53e0593 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=37 digest=sha256:96097c5561c813455a25b9db35c2b0816f7961d070647c382fd3f509a67a7683 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=38 digest=sha256:389713d38773f2e6c67f37667d9ca1007c32ebf3871273bd71eeb2337f2eb933 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=39 digest=sha256:fb49462fcd1bb7029f776c207f06fd74fdfaeab9e390a57d721b64165df75158 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=40 digest=sha256:95a2e258d494fde16dc0c3010cce5d68a096b56cd67f9854bfe4be934ab94679 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=41 digest=sha256:f98a5b7f0147fd279c42eb4a92cb34b76c5c867a4cdc2b5a23c4f3b4218b739a mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=42 digest=sha256:2f3ae3e1448b7f994b4081df2e32e87bf49a8f1283e801574096ac0304f79ff0 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0059] DEBUG layer metadata: index=43 digest=sha256:cd4b37a9e292ae1a376fc844987a43cbefcf4e11a1b101dfe792418ae0762851 mediaType=application/vnd.docker.image.rootfs.diff.tar.gzip
[0064]  INFO identified distro: Ubuntu 22.04.2 LTS
[0064]  INFO cataloging an image
[0064] DEBUG cataloging packages catalogers=17 parallelism=1
[0064] DEBUG discovered 0 packages cataloger=alpmdb-cataloger
[0064] DEBUG discovered 0 packages cataloger=apkdb-cataloger
[0065] DEBUG discovered 4 packages cataloger=binary-cataloger
[0065] DEBUG discovered 362 packages cataloger=dpkgdb-cataloger
[0065] DEBUG found path duplicate of /usr/bin/bunzip2
[0065] DEBUG found path duplicate of /usr/bin/bunzip2
[0065] DEBUG found path duplicate of /usr/bin/gunzip
[0065] DEBUG found path duplicate of /usr/bin/perlbug
[0065] DEBUG found path duplicate of /usr/bin/perl
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/README
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/_msvccompiler.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/archive_util.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/bcppcompiler.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/ccompiler.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/cmd.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/__init__.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/bdist_dumb.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/bdist_rpm.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/build.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/build_clib.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/build_py.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/build_scripts.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/check.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/clean.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/command_template
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/config.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/install.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/install_data.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/install_egg_info.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/install_headers.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/install_lib.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/install_scripts.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/register.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/sdist.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/command/upload.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/core.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/cygwinccompiler.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/debug.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/dep_util.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/dir_util.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/dist.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/errors.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/extension.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/fancy_getopt.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/file_util.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/filelist.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/log.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/msvc9compiler.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/spawn.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/text_file.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/unixccompiler.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/util.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/distutils/versionpredicate.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/Grammar.txt
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/PatternGrammar.txt
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/__main__.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/btm_matcher.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixer_base.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixer_util.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/__init__.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_apply.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_asserts.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_basestring.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_buffer.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_dict.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_except.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_exec.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_execfile.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_exitfunc.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_filter.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_funcattrs.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_future.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_getcwdu.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_has_key.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_idioms.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_import.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_imports.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_imports2.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_input.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_intern.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_isinstance.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_itertools.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_itertools_imports.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_long.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_map.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_metaclass.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_methodattrs.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_ne.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_next.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_nonzero.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_numliterals.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_operator.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_paren.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_print.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_raise.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_raw_input.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_reduce.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_reload.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_renames.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_repr.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_set_literal.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_standarderror.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_sys_exc.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_throw.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_tuple_params.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_types.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_unicode.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_urllib.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_ws_comma.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_xrange.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_xreadlines.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/fixes/fix_zip.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/main.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/patcomp.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pgen2/__init__.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pgen2/conv.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pgen2/driver.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pgen2/literals.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pgen2/parse.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pgen2/pgen.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pgen2/token.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pgen2/tokenize.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pygram.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/pytree.py
[0065] DEBUG found path duplicate of /usr/lib/python3.10/lib2to3/refactor.py
[0065] DEBUG found path duplicate of /usr/bin/unzip
[0066] DEBUG discovered 6 packages cataloger=dotnet-portable-executable-cataloger
[0066] DEBUG discovered 0 packages cataloger=go-module-binary-cataloger
[0066] DEBUG discovered 0 packages cataloger=java-cataloger
[0066] DEBUG discovered 0 packages cataloger=graalvm-native-image-cataloger
[0066] DEBUG discovered 0 packages cataloger=javascript-package-cataloger
[0066] DEBUG discovered 0 packages cataloger=nix-store-cataloger
[0066] DEBUG discovered 0 packages cataloger=php-composer-installed-cataloger
[0066] DEBUG discovered 0 packages cataloger=portage-cataloger
[0066] DEBUG discovered 36 packages cataloger=python-package-cataloger
[0066] DEBUG used CPE dictionary to find CPE for python package "cryptography": cpe:2.3:a:python-cryptography_project:python-cryptography:3.3.2:*:*:*:*:*:*:*
[0066] DEBUG used CPE dictionary to find CPE for python package "cryptography": cpe:2.3:a:python-cryptography_project:python-cryptography:37.0.4:*:*:*:*:*:*:*
[0066] DEBUG used CPE dictionary to find CPE for python package "urllib3": cpe:2.3:a:python:urllib3:1.26.12:*:*:*:*:*:*:*
[0066] DEBUG discovered 0 packages cataloger=r-package-cataloger
[0066] DEBUG discovered 0 packages cataloger=rpm-db-cataloger
[0066] DEBUG discovered 0 packages cataloger=ruby-gemspec-cataloger
[0066] DEBUG discovered 0 packages cataloger=sbom-cataloger`

These are the logs that appear to me and I don't see any errors or I may not be interpreting the logs correctly. When it comes to a public image that this could happen, I can try to find out... But yes, it's very strange...

**Comment by spiffcs** [comment] 2024-06-20 20:12
👋 I used the `nvidia/cuda:12.5.0-devel-rocklinux9 image` to simulate a larger docker image.

It produced a 334149 line SBOM for this image. It did not error out and produced a valid document. 

Closing this for now, but if you still have an image that can reproduce this I can run the test again, but I think this has been fixed.

**Closed by spiffcs** 2024-06-20 20:12 UTC

**Comment by kzantow** [comment] 2024-06-20 22:26
I don't think I've ever been able to reproduce this issue, but I suspect what was happening _may_ have been caused by a race condition that prevented a clean exit. I believe the race condition was fixed as part of this PR: https://github.com/anchore/syft/pull/2161 

If anyone continues to have this issue, please provide an image that would help to reproduce this!
