### ISSUE TITLE
fields are not identical between scans in maven

### ISSUE THREAD

**Issue by tomerse-sg** [anchore/syft#2463] opened 2024-01-02 07:11 UTC
**What happened**:
I'm scanning some private image I have containing jars. I scanned once and got the results, and after that scanned again and some of the data was changed (even though I didn't change the image).
**What you expected to happen**:
the exact same results.
**Steps to reproduce the issue**:
scan an image with jars twice
run diff between json outputs (syft-output).
**Anything else we need to know?**:
I had a similar issue a while ago which I reported and was resolved for a while. maybe something changed between upgrades in syft.
I can't share the image itself but I can share the diff results:
![image](https://github.com/anchore/syft/assets/110396524/87f49055-513a-4666-af73-6d288b6b256f)

Please let me know If you need any additional information.

Thanks!

**Environment**:
- Output of `syft version`: 0.98.0
- OS (e.g: `cat /etc/os-release` or similar): maxOS

**Comment by tgerla** [comment] 2024-01-04 21:19
Hi @tomerse-sg, thank you for the report. We are actually aware of this issue and we're tracking it here: https://github.com/anchore/syft/issues/2405 -- we will hopefully get a fix together soon.

**Comment by kzantow** [comment] 2024-07-30 18:43
I believe this should be fixed in the latest version of Syft 1.10.0, there was an issue identified and fixed, so I'm going to close this issue as I think it's a duplicate of #2967. Please let us know if you still see issues with nondeterminism.

**Closed by kzantow** 2024-07-30 18:43 UTC
Labels: bug
