### ISSUE TITLE
Gemspec file generating empty SBOMs

### ISSUE THREAD

**Issue by diptanshumittal** [anchore/syft#1952] opened 2023-07-25 06:24 UTC
**What happened**:
Empty SBOMs are generated using the *.gemspec file. Syft is not able to detect any package using the gemspec file even tough gemspec is a valid [cataloger](https://github.com/anchore/syft/blob/main/syft/pkg/cataloger/ruby/catalogers.go#L19). 

**What you expected to happen**:
Expected the SBOMs to atleast have a single package with gem details in it. Similar to other languages like Javascript. 

**Steps to reproduce the issue**:
Run `syft packages -o spdx-json` for the [file](https://github.com/googleapis/google-cloud-ruby/blob/76f75470fef3d6969be0048c763438436be466c4/google-cloud-bigtable/google-cloud-bigtable.gemspec)
**Anything else we need to know?**:

**Environment**:
- Output of `syft version`: 0.85.0
- OS (e.g: `cat /etc/os-release` or similar): macOS 13.4.1

**Comment by tgerla** [comment] 2023-08-03 20:53
Hi @diptanshumittal, thank you for the report and the information necessary to reproduce this issue. We'll take a look when we are able.

**Comment by spiffcs** [comment] 2023-08-10 20:12
👋 hey @diptanshumittal!

It looks like it's enabled only for the image cataloger by default
https://github.com/anchore/syft/blob/a90cff1cd21da1422563acf3e5e1ee8a43ba6275/syft/pkg/cataloger/cataloger.go#L42-L62

Can you try updating your configuration code to enable that cataloger. See the configuration here:
https://github.com/anchore/syft#configuration

**Comment by willmurphyscode** [comment] 2023-09-15 19:23
Depending on where the `*.gemspec` file is, it looks like enabling the cataloger still might not find it: https://github.com/anchore/syft/blob/5d48882a787ef55a8df8457bbb62f5bbe9974a8e/syft/pkg/cataloger/ruby/catalogers.go#L19 shows the glob to be `**/specifications/**/*.gemspec`, but if the gem is defined in the directory being scanned, for example, I'm not sure that the gemspec would be under the specifications directory.

See also https://github.com/anchore/syft/issues/2128

**Comment by wagoodman** [comment] 2023-10-19 20:35
I think this might solve the confusion with [this pr/comment](https://github.com/anchore/syft/pull/1971#issuecomment-1690484083), but it's not clear if it is being currently updated or is stale

**Comment by tgerla** [comment] 2023-11-09 15:31
I believe this is fixed thanks to https://github.com/anchore/syft/pull/1971 so I'll close this issue, but feel free to re-open if you are still having problems. Thanks!

**Closed by tgerla** 2023-11-09 15:31 UTC
Labels: bug, changelog-ignore
