### ISSUE TITLE
No Supplier for each component within SBOM

### ISSUE THREAD

**Issue by merlin-uk** [anchore/syft#2993] opened 2024-06-25 10:15 UTC
**What would you like to be added**:
Please add "Supplier" to each component.
**Why is this needed**:
The Supplier is needed to make SBOM valid.
**Additional context**:

**Comment by kzantow** [comment] 2024-06-25 14:28
> The Supplier is needed to make SBOM valid.

This is not required to make a _valid SBOM_. It _is_ required for NTIA minimum elements.

The challenge we have here is that we simply don't have supplier information present in the scan target for everything. However, [we are including supplier, in many cases](https://github.com/anchore/syft/blob/main/syft/format/internal/spdxutil/helpers/originator_supplier.go#L38-L112) if we found this information.

Is there something else you are looking for? Could you provide more information: what package ecosystem, what output format, sample images you expect to have suppliers, etc.?

**Comment by kzantow** [comment] 2024-07-03 19:55
I'm going to close this issue, as I believe it's a duplicate of #1961. If that's not correct, please let me know! And if you have some examples to provide to help us make sure we're surfacing supplier information for ecosystems, please do let us know that as well.

**Closed by kzantow** 2024-07-03 19:55 UTC
Labels: enhancement
