### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by luoyimu1** [anchore/syft#291] opened 2020-12-15 02:10 UTC
**What happened**:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd9aa56]

goroutine 67 [running]:
github.com/anchore/syft/syft/cataloger/java.(*archiveParser).discoverPkgsFromPomProperties(0xc013938b00, 0x0, 0x0, 0x0, 0x117e160, 0xc015ba9b01, 0xc013938b00)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:187 +0x366
github.com/anchore/syft/syft/cataloger/java.(*archiveParser).parse(0xc013938b00, 0x48, 0x14c53e0, 0xc00062ac70, 0x1, 0xc013938b00)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:101 +0xb4
github.com/anchore/syft/syft/cataloger/java.parseJavaArchive(0xc015ba9b30, 0x48, 0x14c53e0, 0xc00062ac70, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:45 +0xf1
github.com/anchore/syft/syft/cataloger/java.(*archiveParser).discoverPkgsFromNestedArchives(0xc00015a000, 0xc023367a00, 0x0, 0x0, 0x1d2e1e0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:266 +0x542
github.com/anchore/syft/syft/cataloger/java.(*archiveParser).parse(0xc00015a000, 0x22, 0x14c5580, 0xc0177d8860, 0x40e501, 0xc00015a000)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:108 +0x147
github.com/anchore/syft/syft/cataloger/java.parseJavaArchive(0xc01761e030, 0x22, 0x14c5580, 0xc0177d8860, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:45 +0xf1
github.com/anchore/syft/syft/cataloger/common.(*GenericCataloger).catalog(0xc01392a340, 0xc022305da0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/common/generic_cataloger.go:104 +0x424
github.com/anchore/syft/syft/cataloger/common.(*GenericCataloger).Catalog(0xc01392a340, 0x14e67e0, 0xc028cd5e40, 0xa, 0xc027cea330, 0xe, 0x11ff6a1, 0xf)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/common/generic_cataloger.go:61 +0xe8
github.com/anchore/syft/syft/cataloger.Catalog(0x14e67e0, 0xc028cd5e40, 0xc01392a280, 0xc013938300, 0x8, 0x8, 0x8, 0x11fabba, 0xb)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/catalog.go:48 +0x107
github.com/anchore/syft/syft.Catalog(0x7ffe39d638ce, 0x42, 0x11f88bd, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/lib.go:65 +0x4e5
github.com/anchore/grype/grype.Catalog(0x7ffe39d638ce, 0x42, 0x11f88bd, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/runner/work/grype/grype/grype/lib.go:48 +0x358
github.com/anchore/grype/cmd.startWorker.func1.2(0xc0005aa760, 0x7ffe39d638ce, 0x42, 0xc00058a1e0, 0xc000164138, 0xc000164140, 0xc0000a7880, 0xc00016c360)
	/Users/runner/work/grype/grype/cmd/root.go:197 +0xd9
created by github.com/anchore/grype/cmd.startWorker.func1
	/Users/runner/work/grype/grype/cmd/root.go:195 +0x227
**What you expected to happen**:
grype should be able to scan the image
**How to reproduce it (as minimally and precisely as possible)**:
Here're the Dockerfile details:
FROM centos7_java_openjdk8:2020.12.1
COPY target/*.jar /opt/app/warehouse-integration.jar
COPY src/main/docker/newrelic.yml /opt/app/newrelic.yml
USER mrdocker
ENTRYPOINT ["/usr/bin/java", "-server", "-jar", "/opt/app/warehouse-integration.jar"]
**Anything else we need to know?**:

**Environment**:
- Output of `syft version`:
- OS (e.g: `cat /etc/os-release` or similar): CentOs 7

**Comment by luhring** [comment] 2020-12-15 19:23
Hi @luoyimu1! I'm trying to reproduce this, but I haven't been able to yet. Do you have guidance on getting a Docker image that would surface this behavior? (E.g., I've tried on `openjdk:8` but it works without issue.)

**Comment by wagoodman** [comment] 2020-12-16 22:26
@luhring I think this occurs when we are attempting to check if the current POM properties file matches attributes from the parent package. We should be ensuring the parent package isn't nil first (since it's possible to not have a parent package). Here's an untested fix https://github.com/anchore/syft/compare/issue-291-java-parent-ref , (I didn't try it out or write a test for it yet... but also wanted to track progress here so it doesn't get lost).

**Comment by wagoodman** [comment] 2020-12-21 13:31
Also, this is a dup of #252

**Comment by giulio1979** [comment] 2021-01-18 14:30
Very similar failure on my end:

[0100] DEBUG cataloger 'rpmdb-cataloger' discovered '0' packages from-lib=syft
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd9aa56]

goroutine 23 [running]:
github.com/anchore/syft/syft/cataloger/java.(*archiveParser).discoverPkgsFromPomProperties(0xc0a34ec980, 0x0, 0x0, 0x0, 0x30, 0x1498cb2, 0x0)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:187 +0x366
github.com/anchore/syft/syft/cataloger/java.(*archiveParser).parse(0xc0a34ec980, 0x30, 0x14c5580, 0xc03338b6a0, 0x40e501, 0xc0a34ec980)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:101 +0xb4
github.com/anchore/syft/syft/cataloger/java.parseJavaArchive(0xc016302c90, 0x30, 0x14c5580, 0xc03338b6a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/java/archive_parser.go:45 +0xf1
github.com/anchore/syft/syft/cataloger/common.(*GenericCataloger).catalog(0xc013dda240, 0xc0e9762870, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/common/generic_cataloger.go:104 +0x424
github.com/anchore/syft/syft/cataloger/common.(*GenericCataloger).Catalog(0xc013dda240, 0x14e6860, 0xc00000e058, 0xc0f3a53fe0, 0x2, 0x2, 0x0, 0x0)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/common/generic_cataloger.go:61 +0xe8
github.com/anchore/syft/syft/cataloger.Catalog(0x14e6860, 0xc00000e058, 0xc013dda100, 0xc013cf8080, 0x8, 0x8, 0xc, 0x11fabba, 0xb)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/cataloger/catalog.go:48 +0x107
github.com/anchore/syft/syft.Catalog(0x7ffcce91053b, 0x9, 0x11f7c8a, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/runner/go/pkg/mod/github.com/anchore/syft@v0.9.2/syft/lib.go:65 +0x4e5
github.com/anchore/grype/grype.Catalog(0x7ffcce91053b, 0x9, 0x11f7c8a, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/runner/work/grype/grype/grype/lib.go:48 +0x358
github.com/anchore/grype/cmd.startWorker.func1.2(0xc013dd3770, 0x7ffcce91053b, 0x9, 0xc013e02320, 0xc00000ec20, 0xc00000ec28, 0xc013e1a770, 0xc0000143c0)
        /Users/runner/work/grype/grype/cmd/root.go:197 +0xd9
created by github.com/anchore/grype/cmd.startWorker.func1
        /Users/runner/work/grype/grype/cmd/root.go:195 +0x227
root@6f71255e9264:/#

**Comment by luhring** [comment] 2021-01-25 02:25
Thanks @giulio1979 and @luoyimu1! As @wagoodman points out, this is a duplicate of #252, so we'll move the discussion over to that issue.

**Closed by luhring** 2021-01-25 02:25 UTC
Labels: bug
